### PR TITLE
remove tic/toc

### PR DESCRIPTION
**Pull request by mdpradeep**
Removed the tic/toc calls to disable printing of elapsed time

### CODE REVIEW

**Comment by ViralBShah** [comment]
@quinnj Can we merge this one? It just prints extra timings otherwise, and one keeps wondering what is being timed. Turns out that the dataframe creation is being timed.

**Comment by mdpradeep** [comment]
Thanks so much.

Regards,
Pradeep

**Comment by quinnj** [comment]
It's actually timing the "fetching" process of transfering the data from the DB to a DataFrame, but I agree that it's pretty cryptic. In the overhaul, I'm going to have this controlled by a keyword argumnet with more features.

**Comment by ViralBShah** [comment]
That would be great!

**Pull request merged**
